/**/sample_signal1:
  ros__parameters:
    frequency: 2.0
    amplitude: 40.0

/**/sample_signal2:
  ros__parameters:
    frequency: 5.0
    amplitude: 20.0    

/**/sample_signal3:
  ros__parameters:
    frequency: 10.0
    amplitude: 10.0                       


/**/sample_signal4:
  ros__parameters:
    frequency: 20.0
    amplitude: 5.0