/**/fft_sample_signal:
  ros__parameters:
    topic: '/hunter_se/test_signal'
    number_of_samples: 1000

/**/fft_filtered_signal:
  ros__parameters:
    topic: 'sample_wave/filtered'
    number_of_samples: 1000